pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/suer/SpinnerHUD")
            credentials {
                Properties localProperties = new Properties()
                def localPropertiesFile = new File(settings.rootDir, 'local.properties')
                if (localPropertiesFile.exists()) {
                    localProperties.load(localPropertiesFile.newDataInputStream())
                }
                username = localProperties['gpr.user'] ?: System.getenv("GPR_USERNAME") ?: ""
                password = localProperties['gpr.key'] ?: System.getenv("GPR_KEY") ?: ""
            }
        }
    }
}

rootProject.name = "android-sample-app"
include ':app'
